package ytb

import (
	"strings"
	"testing"
)

// transcript_test.go reads the caption tracks off a real ANDROID player
// response for dQw4w9WgXcQ. The fixture is that response with everything but
// captions and playabilityStatus.status dropped, which is 8 KB instead of 190 KB
// and leaves the part under test untouched.
//
// The same video asked as WEB answers UNPLAYABLE with no captions at all, so a
// fixture captured from the wrong client would have nothing in it to test.

func TestCaptionsFromAndroidPlayer(t *testing.T) {
	resp := loadFixture(t, "video_captions_android.json")
	if got := playabilityStatus(resp); got != "OK" {
		t.Fatalf("playabilityStatus = %q, want OK", got)
	}
	tracks := ParseCaptionTracks(resp, "dQw4w9WgXcQ")
	if len(tracks) != 6 {
		t.Fatalf("got %d tracks, want the 6 the video carries: %s", len(tracks), trackSummary(tracks))
	}

	byVss := map[string]CaptionTrack{}
	for _, tr := range tracks {
		byVss[tr.VssID] = tr
		if tr.VideoID != "dQw4w9WgXcQ" {
			t.Errorf("track %s carries VideoID %q", tr.VssID, tr.VideoID)
		}
		// YouTube picked srv3 for itself. Nothing here asks for a format, and a
		// baseUrl that stopped ending this way would mean pkg/srv3 is being handed
		// something else.
		if !strings.HasSuffix(tr.BaseURL, "&fmt=srv3") {
			t.Errorf("track %s baseUrl does not end in &fmt=srv3: %s", tr.VssID, tr.BaseURL)
		}
	}

	// ".en" and "a.en" are the same language and different tracks. vssId is the
	// only field that separates them, which is why it is on the record.
	human, ok := byVss[".en"]
	if !ok {
		t.Fatal("no .en track, which is the human English one")
	}
	if human.IsAutoGenerated {
		t.Error(".en is marked auto-generated; kind is absent on a human track")
	}
	if human.Name != "English" {
		t.Errorf("human name = %q, want English", human.Name)
	}
	auto, ok := byVss["a.en"]
	if !ok {
		t.Fatal("no a.en track, which is the machine English one")
	}
	if !auto.IsAutoGenerated {
		t.Error("a.en is not marked auto-generated; its kind is asr")
	}
	if auto.Name != "English (auto-generated)" {
		t.Errorf("auto name = %q", auto.Name)
	}

	// translationLanguages is a property of the video, and it is stamped on every
	// translatable track so a caller holding one track knows what it can ask for.
	if len(human.TranslatableTo) != 18 {
		t.Errorf("TranslatableTo = %d languages, want the 18 offered", len(human.TranslatableTo))
	}
	if !contains(human.TranslatableTo, "vi") {
		t.Errorf("TranslatableTo has no vi: %v", human.TranslatableTo)
	}
}

func TestPickCaptionTrack(t *testing.T) {
	tracks := ParseCaptionTracks(loadFixture(t, "video_captions_android.json"), "dQw4w9WgXcQ")

	cases := []struct {
		label string
		opt   TranscriptOptions
		want  string // the vssId expected, or "" for no track
	}{
		// No language asked for takes the human track, because the machine one is a
		// wall of unpunctuated words and both are on this video.
		{"default", TranscriptOptions{}, ".en"},
		{"auto", TranscriptOptions{Auto: true}, "a.en"},
		{"exact", TranscriptOptions{Lang: "ja"}, ".ja"},
		// es-419 is the only Spanish here, and someone asking for "es" means it.
		{"prefix", TranscriptOptions{Lang: "es"}, ".es-419"},
		// Nothing auto in German, so the human track answers rather than the video
		// reading as having no German at all.
		{"auto falls back", TranscriptOptions{Lang: "de", Auto: true}, ".de-DE"},
		{"no such language", TranscriptOptions{Lang: "zz"}, ""},
	}
	for _, c := range cases {
		got := pickCaptionTrack(tracks, c.opt)
		switch {
		case c.want == "" && got != nil:
			t.Errorf("%s: got %s, want no track", c.label, got.VssID)
		case c.want == "":
		case got == nil:
			t.Errorf("%s: got no track, want %s", c.label, c.want)
		case got.VssID != c.want:
			t.Errorf("%s: got %s, want %s", c.label, got.VssID, c.want)
		}
	}
}

// TestTrackSummaryNamesWhatIsThere covers the sentence a caller reads after
// asking for a language the video does not have. Listing what it does have is
// the whole point of the error.
func TestTrackSummaryNamesWhatIsThere(t *testing.T) {
	tracks := ParseCaptionTracks(loadFixture(t, "video_captions_android.json"), "dQw4w9WgXcQ")
	got := trackSummary(tracks)
	for _, want := range []string{"en", "en (auto)", "ja", "es-419"} {
		if !strings.Contains(got, want) {
			t.Errorf("trackSummary = %q, missing %q", got, want)
		}
	}
}
