package ytb

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/tamnd/ytb-cli/pkg/srv3"
)

// transcript.go is the caption plane. Doc 01 section 3, doc 05 section 4.
//
// There is one thing to know about captions and it decides the whole design: a
// caption baseUrl is only good if it came from a mobile player.
//
// Measured on dQw4w9WgXcQ, all three on the same minute:
//
//	/player as WEB      playabilityStatus UNPLAYABLE, 0 caption tracks
//	/player as ANDROID  OK, 6 tracks, baseUrl fetches 4123 bytes
//	the watch page      6 tracks listed, baseUrl fetches HTTP 200 and 0 bytes
//
// The watch page is the trap. It lists every track with a plausible signed URL
// that answers 200 with an empty body, forever, whatever fmt you ask for, and
// stripping the exp=xpe it carries only breaks the signature into a 404. That
// empty 200 is why this tool used to shell out to yt-dlp and Deno for text the
// ANDROID player hands over in one request. The fix was the client, not a
// subprocess.
//
// The bytes are srv3 and pkg/srv3 parses them. The baseUrl already ends in
// &fmt=srv3, so that is not a conversion we asked for, it is the format YouTube
// picked for itself.

// ErrNoCaptions is the answer when a video genuinely has no caption track.
//
// It is not a Refusal. YouTube did not decline anything: aqz-KE-bpKQ answers OK
// with an empty captionTracks list, because nobody ever wrote captions for it.
// "There are none" and "we will not give you these" are different answers and
// they get different exit codes.
var ErrNoCaptions = errors.New("this video has no caption track")

// ErrNoSuchCaptionTrack is the answer when the video has captions but not the
// ones asked for. It is a separate sentinel from ErrNoCaptions because the two
// sentences a reader needs are different: one says write your own, the other
// says pick from this list.
var ErrNoSuchCaptionTrack = errors.New("no caption track in that language")

// Captions returns the caption tracks for a video, from the ANDROID player.
//
// Nothing here reads the watch page. The page lists the same tracks with URLs
// that do not work, and returning them would be handing the caller something
// that looks like an answer.
func (c *Client) Captions(ctx context.Context, idOrURL string) ([]CaptionTrack, error) {
	videoID := ExtractVideoID(idOrURL)
	if videoID == "" {
		videoID = idOrURL
	}
	resp, err := NewInnerTube(c).AndroidPlayer(ctx, videoID)
	if err != nil {
		return nil, fmt.Errorf("caption tracks for %s: %w", videoID, err)
	}
	if st := playabilityStatus(resp); st != "" && st != "OK" {
		// The player declining is YouTube's own answer and it says why in its own
		// words, so those words are what the user sees.
		msg := stringValue(mapValue(resp, "playabilityStatus")["reason"])
		if msg == "" {
			msg = st
		}
		return nil, newRefusal("captions for "+videoID, "player as ANDROID", msg)
	}
	return ParseCaptionTracks(resp, videoID), nil
}

// playabilityStatus reports what the player said about the video, which is the
// difference between "no captions" and "we were not given the video".
func playabilityStatus(resp map[string]any) string {
	return stringValue(mapValue(resp, "playabilityStatus")["status"])
}

// ParseCaptionTracks reads the caption track list off a player response. The
// text is a separate read; this is the index.
func ParseCaptionTracks(playerResp map[string]any, videoID string) []CaptionTrack {
	renderer := mapValue(mapValue(playerResp, "captions"), "playerCaptionsTracklistRenderer")
	if renderer == nil {
		return nil
	}
	var tracks []CaptionTrack
	for _, item := range arrayValue(renderer["captionTracks"]) {
		m := mapValue(item, "")
		kind := stringValue(m["kind"])
		ct := CaptionTrack{
			VideoID:      videoID,
			LanguageCode: stringValue(m["languageCode"]),
			Name:         extractText(m["name"]),
			BaseURL:      stringValue(m["baseUrl"]),
			TrackKind:    kind,
			// kind is "asr" on a machine track and absent on a human one. An absent
			// string is not an answer to "was this typed by a person", so the boolean
			// is stated rather than left to the caller to infer.
			IsAutoGenerated: kind == "asr",
			// vssId is the track's own name for itself: ".en" for the human English
			// track and "a.en" for the machine one. It is the only field that tells
			// two same-language tracks apart in a stable way.
			VssID:          stringValue(m["vssId"]),
			TrackName:      stringValue(m["trackName"]),
			IsTranslatable: boolValue(m["isTranslatable"]),
		}
		if ct.LanguageCode != "" && ct.BaseURL != "" {
			tracks = append(tracks, ct)
		}
	}
	// The translation languages are a property of the video and not of any one
	// track, so they are stamped on each track that can be translated rather than
	// returned as a second thing the caller has to hold.
	var langs []string
	for _, item := range arrayValue(renderer["translationLanguages"]) {
		if code := stringValue(mapValue(item, "")["languageCode"]); code != "" {
			langs = append(langs, code)
		}
	}
	if len(langs) > 0 {
		for i := range tracks {
			if tracks[i].IsTranslatable {
				tracks[i].TranslatableTo = langs
			}
		}
	}
	return tracks
}

// TranscriptOptions selects and shapes one caption read.
type TranscriptOptions struct {
	// Lang picks the track by language code. Empty takes the default, which is a
	// human track over a machine one.
	Lang string
	// Auto forces the auto-generated track even when a human one exists.
	Auto bool
	// TranslateTo asks YouTube to machine-translate the chosen track. The
	// translation is the site's, not ours.
	TranslateTo string
}

// Transcript fetches one caption track and returns it parsed.
//
// The Document carries the cues, the word timings an auto track states, and the
// head, so a caller can write text, srt, vtt or json off one read.
func (c *Client) Transcript(ctx context.Context, idOrURL string, opt TranscriptOptions) (*srv3.Document, CaptionTrack, error) {
	tracks, err := c.Captions(ctx, idOrURL)
	if err != nil {
		return nil, CaptionTrack{}, err
	}
	if len(tracks) == 0 {
		// The id goes after the sentence and not in front of it. fang title-cases the
		// first word of an error before printing it, and cases.Title breaks on
		// hyphens, so an id leading the line comes out as "Aqz-Ke-Bpkq" instead of
		// aqz-KE-bpKQ, which is an id nobody can paste back.
		return nil, CaptionTrack{}, fmt.Errorf("%w: %s", ErrNoCaptions, idOrURL)
	}
	track := pickCaptionTrack(tracks, opt)
	if track == nil {
		return nil, CaptionTrack{}, fmt.Errorf("%w for %q, the video has %s",
			ErrNoSuchCaptionTrack, opt.Lang, trackSummary(tracks))
	}

	url := track.BaseURL
	if opt.TranslateTo != "" {
		url += "&tlang=" + opt.TranslateTo
	}
	raw, err := c.FetchTimedText(ctx, url)
	if err != nil {
		return nil, *track, fmt.Errorf("fetch timed text: %w", err)
	}
	doc, err := srv3.Parse(raw)
	if errors.Is(err, srv3.ErrEmpty) {
		// The endpoint refuses by answering 200 with nothing. It does that for a
		// URL off the watch page every time, and for a good URL with a language
		// asked for that the track cannot be translated into. An empty body is not
		// an empty transcript, so it exits like the refusal it is.
		return nil, *track, newRefusal(
			fmt.Sprintf("the %s track of %s", track.LanguageCode, track.VideoID),
			"timedtext", "the endpoint answered HTTP 200 with no bytes")
	}
	if err != nil {
		return nil, *track, err
	}
	return doc, *track, nil
}

// pickCaptionTrack chooses the track to read.
//
// With no language asked for it takes a human track over a machine one, because
// a video that has both has a person's punctuation in one of them and a wall of
// unpunctuated words in the other.
func pickCaptionTrack(tracks []CaptionTrack, opt TranscriptOptions) *CaptionTrack {
	match := func(t CaptionTrack) bool {
		if opt.Auto != t.IsAutoGenerated {
			return false
		}
		switch {
		case opt.Lang == "":
			return true
		case t.LanguageCode == opt.Lang:
			return true
		// "en" should find "en-GB" when there is no plain "en", which is what a
		// person asking for English means.
		default:
			return strings.HasPrefix(t.LanguageCode, opt.Lang+"-")
		}
	}
	// Exact language before prefix, and the requested kind before the other one.
	for _, exact := range []bool{true, false} {
		for i := range tracks {
			if !match(tracks[i]) {
				continue
			}
			if exact && opt.Lang != "" && tracks[i].LanguageCode != opt.Lang {
				continue
			}
			return &tracks[i]
		}
	}
	// Nothing of the kind asked for. Fall back to the other kind rather than
	// telling a caller with one auto track that the video has no captions, and the
	// same the other way: --auto --lang de on a video whose only German track was
	// typed by a person is a request for the German, not a request for nothing.
	// The chosen track goes back to the caller, so what was read is never a guess.
	for i := range tracks {
		if opt.Lang == "" || tracks[i].LanguageCode == opt.Lang ||
			strings.HasPrefix(tracks[i].LanguageCode, opt.Lang+"-") {
			return &tracks[i]
		}
	}
	return nil
}

// trackSummary names what the video does have, for the error a caller reads
// after asking for a language it does not.
func trackSummary(tracks []CaptionTrack) string {
	seen := map[string]bool{}
	var codes []string
	for _, t := range tracks {
		label := t.LanguageCode
		if t.IsAutoGenerated {
			label += " (auto)"
		}
		if !seen[label] {
			seen[label] = true
			codes = append(codes, label)
		}
	}
	sort.Strings(codes)
	return strings.Join(codes, ", ")
}

// TranscriptSegments flattens a document into the timed segments the store and
// the sidecar writers hold.
func TranscriptSegments(doc *srv3.Document) []TranscriptSegment {
	if doc == nil {
		return nil
	}
	out := make([]TranscriptSegment, 0, len(doc.Cues))
	for _, c := range doc.Cues {
		out = append(out, TranscriptSegment{
			StartSeconds: float64(c.StartMS) / 1000,
			DurSeconds:   float64(c.DurMS) / 1000,
			Text:         c.Text,
		})
	}
	return out
}

// Formats returns the streaming formats for a video.
//
// Like Captions this asks a mobile player, because the WEB /player answers
// UNPLAYABLE with no streamingData on it at all.
func (c *Client) Formats(ctx context.Context, idOrURL string) ([]VideoFormat, error) {
	videoID := ExtractVideoID(idOrURL)
	if videoID == "" {
		videoID = idOrURL
	}
	return ParseVideoFormats(c.playerResponse(ctx, idOrURL, videoID), videoID), nil
}

// playerResponse returns the best available player response for a video: the
// ANDROID player first, then the watch page's embedded one, then WEB.
func (c *Client) playerResponse(ctx context.Context, idOrURL, videoID string) map[string]any {
	if pr, err := NewInnerTube(c).AndroidPlayer(ctx, videoID); err == nil && playabilityStatus(pr) == "OK" {
		return pr
	}
	if data, _, err := c.FetchPageData(ctx, NormalizeVideoURL(idOrURL)); err == nil && data != nil {
		if pr, ok := data.PlayerResp.(map[string]any); ok && pr != nil {
			return pr
		}
	}
	if pr, err := NewInnerTube(c).Player(ctx, videoID); err == nil {
		return pr
	}
	return nil
}
