package cli

import (
	"strconv"

	"github.com/tamnd/ytb-cli/youtube"
)

func itoa(n int) string   { return strconv.Itoa(n) }
func i64a(n int64) string { return strconv.FormatInt(n, 10) }
func boola(b bool) string { return strconv.FormatBool(b) }

func videoRow(v youtube.Video) Row {
	return Row{
		Cols: []string{"id", "title", "channel", "duration", "views", "published", "url"},
		Vals: []string{
			v.VideoID, v.Title, v.ChannelName, v.DurationText,
			i64a(v.ViewCount), v.PublishedText, v.URL,
		},
		Value: v,
	}
}

func channelRow(c youtube.Channel) Row {
	return Row{
		Cols: []string{"id", "handle", "title", "subscribers", "videos", "url"},
		Vals: []string{
			c.ChannelID, c.Handle, c.Title, c.SubscribersText, c.VideosText, c.URL,
		},
		Value: c,
	}
}

func playlistRow(p youtube.Playlist) Row {
	return Row{
		Cols: []string{"id", "title", "channel", "videos", "url"},
		Vals: []string{
			p.PlaylistID, p.Title, p.ChannelName, itoa(p.VideoCount), p.URL,
		},
		Value: p,
	}
}

func formatRow(f youtube.VideoFormat) Row {
	res := f.QualityLabel
	if res == "" {
		res = f.Quality
	}
	return Row{
		Cols: []string{"itag", "mime", "quality", "fps", "bitrate", "size", "adaptive"},
		Vals: []string{
			itoa(f.ITag), f.MimeType, res, itoa(f.FPS),
			i64a(f.Bitrate), i64a(f.ContentLength), boola(f.IsAdaptive),
		},
		Value: f,
	}
}

func captionRow(t youtube.CaptionTrack) Row {
	return Row{
		Cols:  []string{"language_code", "name", "auto", "url"},
		Vals:  []string{t.LanguageCode, t.Name, boola(t.IsAutoGenerated), t.BaseURL},
		Value: t,
	}
}

func segmentRow(s youtube.TranscriptSegment) Row {
	return Row{
		Cols: []string{"start", "dur", "text"},
		Vals: []string{
			strconv.FormatFloat(s.StartSeconds, 'f', 2, 64),
			strconv.FormatFloat(s.DurSeconds, 'f', 2, 64),
			s.Text,
		},
		Value: s,
	}
}

func queueRow(q youtube.QueueItem) Row {
	return Row{
		Cols: []string{"id", "url", "entity_type", "status", "priority"},
		Vals: []string{
			i64a(q.ID), q.URL, q.EntityType, q.Status, itoa(q.Priority),
		},
		Value: q,
	}
}

func jobRow(j youtube.JobRecord) Row {
	return Row{
		Cols: []string{"job_id", "name", "type", "status", "started", "completed"},
		Vals: []string{
			j.JobID, j.Name, j.Type, j.Status,
			j.StartedAt.Format("2006-01-02T15:04:05Z"),
			j.CompletedAt.Format("2006-01-02T15:04:05Z"),
		},
		Value: j,
	}
}

func artistRow(a youtube.Artist) Row {
	return Row{
		Cols:  []string{"id", "name", "subscribers", "url"},
		Vals:  []string{a.ArtistID, a.Name, a.SubscribersText, a.URL},
		Value: a,
	}
}

func albumRow(a youtube.Album) Row {
	return Row{
		Cols: []string{"id", "title", "artist", "year", "tracks", "url"},
		Vals: []string{
			a.AlbumID, a.Title, a.ArtistName, a.Year, itoa(a.TrackCount), a.URL,
		},
		Value: a,
	}
}

func songRow(s youtube.Song) Row {
	return Row{
		Cols: []string{"id", "title", "artist", "album", "duration", "url"},
		Vals: []string{
			s.VideoID, s.Title, s.ArtistName, s.AlbumName, s.DurationText, s.URL,
		},
		Value: s,
	}
}

// anyRow renders a polymorphic search emission (Video/Channel/Playlist/Artist/Album/Song).
func anyRow(v any) Row {
	switch x := v.(type) {
	case youtube.Video:
		return videoRow(x)
	case youtube.Channel:
		return channelRow(x)
	case youtube.Playlist:
		return playlistRow(x)
	case youtube.Artist:
		return artistRow(x)
	case youtube.Album:
		return albumRow(x)
	case youtube.Song:
		return songRow(x)
	default:
		return Row{Cols: []string{"value"}, Vals: []string{""}, Value: v}
	}
}
