package cli

import (
	"strconv"
	"strings"

	"github.com/tamnd/ytb-cli/ytb"
)

func itoa(n int) string   { return strconv.Itoa(n) }
func i64a(n int64) string { return strconv.FormatInt(n, 10) }
func boola(b bool) string { return strconv.FormatBool(b) }

// oneline flattens a value to a single short line for a curated column, so a
// multi-line title or comment body never breaks the list and table layouts.
func oneline(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	if len(s) > 80 {
		return s[:79] + "..."
	}
	return s
}

// nodeRow renders a graph node discovered by `ytb discover`. The curated columns
// read the walk at a glance (how deep, by which edge, and a one-line who/what)
// while the full typed node (with the nested video, channel, playlist, comment,
// or post) rides in Value for json, jsonl, and templates.
func nodeRow(n *ytb.Node) Row {
	var id, who, summary, url string
	switch n.Kind {
	case ytb.KindVideo:
		v := n.Video
		id = v.VideoID
		who = v.ChannelTitle
		summary = oneline(v.Title)
		url = v.URL
		if url == "" {
			url = "https://www.youtube.com/watch?v=" + v.VideoID
		}
	case ytb.KindChannel:
		c := n.Channel
		id = c.ChannelID
		who = c.Handle
		if who == "" {
			who = c.Title
		}
		summary = oneline(c.Title)
		url = c.URL
	case ytb.KindPlaylist:
		p := n.Playlist
		id = p.PlaylistID
		who = p.ChannelTitle
		summary = oneline(p.Title)
		url = p.URL
	case ytb.KindComment:
		c := n.Comment
		id = c.ID
		who = c.AuthorDisplayName
		summary = oneline(c.TextDisplay)
	case ytb.KindPost:
		p := n.Post
		id = p.PostID
		who = p.AuthorName
		summary = oneline(p.ContentText)
	}
	return Row{
		Cols:  []string{"depth", "via", "kind", "id", "who", "summary", "url"},
		Vals:  []string{itoa(n.Depth), string(n.Via), string(n.Kind), id, who, summary, url},
		Value: n,
	}
}

func videoRow(v ytb.Video) Row {
	return Row{
		Cols: []string{"id", "title", "channel", "duration", "views", "published", "url"},
		Vals: []string{
			v.VideoID, v.Title, v.ChannelTitle, v.DurationText,
			i64a(v.ViewCount), v.PublishedText, v.URL,
		},
		Value: v,
	}
}

func channelRow(c ytb.Channel) Row {
	return Row{
		Cols: []string{"id", "handle", "title", "subscribers", "videos", "url"},
		Vals: []string{
			c.ChannelID, c.Handle, c.Title, c.SubscriberCountText, c.VideoCountText, c.URL,
		},
		Value: c,
	}
}

func playlistRow(p ytb.Playlist) Row {
	return Row{
		Cols: []string{"id", "title", "channel", "videos", "url"},
		Vals: []string{
			p.PlaylistID, p.Title, p.ChannelTitle, itoa(int(p.VideoCount)), p.URL,
		},
		Value: p,
	}
}

// formatRow renders one stream. The columns are the ones a person choosing a
// format reads: what it is, what it plays as, how big it is, and whatever is odd
// about it. mime and adaptive are gone from the table because kind, container and
// codec say the same three things in a form that fits, and both are still in the
// json.
func formatRow(f ytb.VideoFormat) Row {
	return Row{
		Cols: []string{"itag", "kind", "container", "quality", "codec", "bitrate", "size", "note"},
		Vals: []string{
			itoa(f.ITag), f.MediaKind, f.Container, f.QualityText(), f.Codec,
			bitrateText(f.Bitrate), sizeText(f.ContentLength), f.Note,
		},
		Value: f,
	}
}

// bitrateText renders bits per second the way a codec table does: 129k, 4.3M.
func bitrateText(bps int64) string {
	switch {
	case bps <= 0:
		return ""
	case bps >= 1_000_000:
		return strconv.FormatFloat(float64(bps)/1_000_000, 'f', 1, 64) + "M"
	case bps >= 1_000:
		return strconv.FormatInt(bps/1_000, 10) + "k"
	default:
		return i64a(bps)
	}
}

// sizeText renders a content length, and renders an absent one as nothing rather
// than as 0B. See VideoFormat.Note: a muxed format has no contentLength on the
// mobile player, and a 0 there would read as an empty file.
func sizeText(n int64) string {
	if n <= 0 {
		return ""
	}
	return humanBytes(n)
}

// captionRow shows vss_id in the table because it is the field that separates
// two tracks in the same language: ".en" is the human one and "a.en" the
// machine one, and the name column translates while the vss id does not.
func captionRow(t ytb.CaptionTrack) Row {
	return Row{
		Cols:  []string{"language_code", "vss_id", "name", "auto", "translatable"},
		Vals:  []string{t.LanguageCode, t.VssID, t.Name, boola(t.IsAutoGenerated), boola(t.IsTranslatable)},
		Value: t,
	}
}

func artistRow(a ytb.Artist) Row {
	return Row{
		Cols:  []string{"id", "name", "subscribers", "url"},
		Vals:  []string{a.ArtistID, a.Name, a.SubscriberCountText, a.URL},
		Value: a,
	}
}

func albumRow(a ytb.Album) Row {
	return Row{
		Cols: []string{"id", "title", "artist", "year", "tracks", "url"},
		Vals: []string{
			a.AlbumID, a.Title, credits(a.ArtistNames), a.Year, itoa(a.TrackCount), a.URL,
		},
		Value: a,
	}
}

func trackRow(t ytb.Track) Row {
	return Row{
		Cols: []string{"id", "title", "artist", "album", "duration", "url"},
		Vals: []string{
			t.VideoID, t.Title, credits(t.ArtistNames), t.AlbumTitle, t.DurationText, t.URL,
		},
		Value: t,
	}
}

// musicItemRow renders one lockup off an artist page.
func musicItemRow(m ytb.MusicItem) Row {
	kind := m.Kind
	if m.AlbumType != "" {
		kind = strings.ToLower(m.AlbumType)
	}
	return Row{
		Cols:  []string{"kind", "id", "title", "shelf", "year", "url"},
		Vals:  []string{kind, m.ID, m.Title, m.Shelf, m.Year, m.URL},
		Value: m,
	}
}

// musicResultRow renders one row of a music search, whatever kind it is.
//
// A music search comes back interleaved: a song, then a playlist, then an
// album. The table renderer takes its header from the first record it sees and
// lays every later one out under it, so four row shapes in one stream print
// four values under the wrong four headings. One shape for the whole stream is
// what fixes that. The detail column is whatever that kind's own line said, a
// duration for a track and a year for an album, and -o json still carries the
// full record with all of its fields.
func musicResultRow(v any) Row {
	f, ok := musicFields(v)
	if !ok {
		return anyRow(v)
	}
	return Row{
		Cols:  []string{"kind", "id", "title", "artist", "detail", "url"},
		Vals:  []string{f.kind, f.id, f.title, f.artist, f.detail, f.url},
		Value: v,
	}
}

// musicShelfRow is musicResultRow with the shelf the row came off, which is
// what an artist page adds and a search does not have.
func musicShelfRow(v any, shelf string) Row {
	f, ok := musicFields(v)
	if !ok {
		return anyRow(v)
	}
	if f.shelf == "" {
		f.shelf = shelf
	}
	return Row{
		Cols:  []string{"kind", "id", "title", "artist", "detail", "shelf", "url"},
		Vals:  []string{f.kind, f.id, f.title, f.artist, f.detail, f.shelf, f.url},
		Value: v,
	}
}

// musicFace is what every music record has in common once it is a table row.
type musicFace struct{ kind, id, title, artist, detail, shelf, url string }

func musicFields(v any) (musicFace, bool) {
	var f musicFace
	switch x := v.(type) {
	case ytb.Track:
		// ATV is an art track, which is a song. Anything else is a video of one,
		// and the music app types it rather than saying so in words. Both are the
		// same record, so this column is the only place the difference shows.
		f.kind = "track"
		if x.MusicVideoType != "" && x.MusicVideoType != "ATV" {
			f.kind = "video"
		}
		f.id, f.title = x.VideoID, x.Title
		f.artist, f.detail, f.url = credits(x.ArtistNames), x.DurationText, x.URL
		if f.detail == "" {
			f.detail = x.PlaysText
		}
		if f.detail == "" && len(x.MetadataParts) > 0 {
			f.detail = x.MetadataParts[0]
		}
	case ytb.Album:
		f.kind, f.id, f.title = "album", x.AlbumID, x.Title
		f.artist, f.detail, f.url = credits(x.ArtistNames), x.Year, x.URL
		if x.AlbumType != "" {
			f.kind = strings.ToLower(x.AlbumType)
		}
	case ytb.Artist:
		f.kind, f.id, f.title = "artist", x.ArtistID, x.Name
		f.detail, f.url = x.SubscriberCountText, x.URL
		if f.detail == "" && len(x.MetadataParts) > 0 {
			f.detail = x.MetadataParts[0]
		}
	case ytb.Playlist:
		f.kind, f.id, f.title = "playlist", x.PlaylistID, x.Title
		f.artist, f.url = x.ChannelTitle, x.URL
		f.detail = x.VideoCountText
		if f.detail == "" && len(x.MetadataParts) > 0 {
			f.detail = x.MetadataParts[0]
		}
	case ytb.MusicItem:
		f.kind, f.id, f.title = x.Kind, x.ID, x.Title
		if x.MusicVideoType != "" && x.MusicVideoType != "ATV" {
			f.kind = "video"
		}
		f.artist, f.shelf, f.url = credits(x.ArtistNames), x.Shelf, x.URL
		f.detail = x.Year
		if f.detail == "" {
			f.detail = x.CountText
		}
		if x.AlbumType != "" {
			f.kind = strings.ToLower(x.AlbumType)
		}
	default:
		return f, false
	}
	return f, true
}

// credits joins the artist names for one table cell. The record keeps them
// apart, because a release credited to two people is two credits and not a name
// with an ampersand in it, and a table cell is one string either way.
func credits(names []string) string {
	return strings.Join(names, ", ")
}

// anyRow renders a polymorphic search emission (Video/Channel/Playlist/Artist/Album/Track).
func anyRow(v any) Row {
	switch x := v.(type) {
	case ytb.Video:
		return videoRow(x)
	case ytb.Channel:
		return channelRow(x)
	case ytb.Playlist:
		return playlistRow(x)
	case ytb.Artist:
		return artistRow(x)
	case ytb.Album:
		return albumRow(x)
	case ytb.Track:
		return trackRow(x)
	case ytb.MusicItem:
		return musicItemRow(x)
	default:
		return Row{Cols: []string{"value"}, Vals: []string{""}, Value: v}
	}
}
