package cli

import (
	"strconv"
	"strings"

	"github.com/tamnd/ytb-cli/youtube"
)

func itoa(n int) string   { return strconv.Itoa(n) }
func i64a(n int64) string { return strconv.FormatInt(n, 10) }
func boola(b bool) string { return strconv.FormatBool(b) }

// oneline flattens a value to a single short line for a curated column, so a
// multi-line title or comment body never breaks the list and table layouts.
func oneline(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	if len(s) > 80 {
		return s[:79] + "..."
	}
	return s
}

// nodeRow renders a graph node discovered by `ytb discover`. The curated columns
// read the walk at a glance (how deep, by which edge, and a one-line who/what)
// while the full typed node (with the nested video, channel, playlist, comment,
// or post) rides in Value for json, jsonl, and templates.
func nodeRow(n *youtube.Node) Row {
	var id, who, summary, url string
	switch n.Kind {
	case youtube.KindVideo:
		v := n.Video
		id = v.VideoID
		who = v.ChannelTitle
		summary = oneline(v.Title)
		url = v.URL
		if url == "" {
			url = "https://www.youtube.com/watch?v=" + v.VideoID
		}
	case youtube.KindChannel:
		c := n.Channel
		id = c.ChannelID
		who = c.Handle
		if who == "" {
			who = c.Title
		}
		summary = oneline(c.Title)
		url = c.URL
	case youtube.KindPlaylist:
		p := n.Playlist
		id = p.PlaylistID
		who = p.ChannelName
		summary = oneline(p.Title)
		url = p.URL
	case youtube.KindComment:
		c := n.Comment
		id = c.ID
		who = c.AuthorDisplayName
		summary = oneline(c.TextDisplay)
	case youtube.KindPost:
		p := n.Post
		id = p.PostID
		who = p.AuthorName
		summary = oneline(p.ContentText)
	}
	return Row{
		Cols:  []string{"depth", "via", "kind", "id", "who", "summary", "url"},
		Vals:  []string{itoa(n.Depth), string(n.Via), string(n.Kind), id, who, summary, url},
		Value: n,
	}
}

func videoRow(v youtube.Video) Row {
	return Row{
		Cols: []string{"id", "title", "channel", "duration", "views", "published", "url"},
		Vals: []string{
			v.VideoID, v.Title, v.ChannelTitle, v.DurationText,
			i64a(v.ViewCount), v.PublishedText, v.URL,
		},
		Value: v,
	}
}

func channelRow(c youtube.Channel) Row {
	return Row{
		Cols: []string{"id", "handle", "title", "subscribers", "videos", "url"},
		Vals: []string{
			c.ChannelID, c.Handle, c.Title, c.SubscriberCountText, c.VideoCountText, c.URL,
		},
		Value: c,
	}
}

func playlistRow(p youtube.Playlist) Row {
	return Row{
		Cols: []string{"id", "title", "channel", "videos", "url"},
		Vals: []string{
			p.PlaylistID, p.Title, p.ChannelName, itoa(p.VideoCount), p.URL,
		},
		Value: p,
	}
}

// formatRow renders one stream. The columns are the ones a person choosing a
// format reads: what it is, what it plays as, how big it is, and whatever is odd
// about it. mime and adaptive are gone from the table because kind, container and
// codec say the same three things in a form that fits, and both are still in the
// json.
func formatRow(f youtube.VideoFormat) Row {
	return Row{
		Cols: []string{"itag", "kind", "container", "quality", "codec", "bitrate", "size", "note"},
		Vals: []string{
			itoa(f.ITag), f.Kind, f.Container, f.QualityText(), f.Codec,
			bitrateText(f.Bitrate), sizeText(f.ContentLength), f.Note,
		},
		Value: f,
	}
}

// bitrateText renders bits per second the way a codec table does: 129k, 4.3M.
func bitrateText(bps int64) string {
	switch {
	case bps <= 0:
		return ""
	case bps >= 1_000_000:
		return strconv.FormatFloat(float64(bps)/1_000_000, 'f', 1, 64) + "M"
	case bps >= 1_000:
		return strconv.FormatInt(bps/1_000, 10) + "k"
	default:
		return i64a(bps)
	}
}

// sizeText renders a content length, and renders an absent one as nothing rather
// than as 0B. See VideoFormat.Note: a muxed format has no contentLength on the
// mobile player, and a 0 there would read as an empty file.
func sizeText(n int64) string {
	if n <= 0 {
		return ""
	}
	return humanBytes(n)
}

func captionRow(t youtube.CaptionTrack) Row {
	return Row{
		Cols:  []string{"language_code", "name", "auto", "url"},
		Vals:  []string{t.LanguageCode, t.Name, boola(t.IsAutoGenerated), t.BaseURL},
		Value: t,
	}
}

func segmentRow(s youtube.TranscriptSegment) Row {
	return Row{
		Cols: []string{"start", "dur", "text"},
		Vals: []string{
			strconv.FormatFloat(s.StartSeconds, 'f', 2, 64),
			strconv.FormatFloat(s.DurSeconds, 'f', 2, 64),
			s.Text,
		},
		Value: s,
	}
}

func queueRow(q youtube.QueueItem) Row {
	return Row{
		Cols: []string{"id", "url", "entity_type", "status", "priority"},
		Vals: []string{
			i64a(q.ID), q.URL, q.EntityType, q.Status, itoa(q.Priority),
		},
		Value: q,
	}
}

func jobRow(j youtube.JobRecord) Row {
	return Row{
		Cols: []string{"job_id", "name", "type", "status", "started", "completed"},
		Vals: []string{
			j.JobID, j.Name, j.Type, j.Status,
			j.StartedAt.Format("2006-01-02T15:04:05Z"),
			j.CompletedAt.Format("2006-01-02T15:04:05Z"),
		},
		Value: j,
	}
}

func artistRow(a youtube.Artist) Row {
	return Row{
		Cols:  []string{"id", "name", "subscribers", "url"},
		Vals:  []string{a.ArtistID, a.Name, a.SubscribersText, a.URL},
		Value: a,
	}
}

func albumRow(a youtube.Album) Row {
	return Row{
		Cols: []string{"id", "title", "artist", "year", "tracks", "url"},
		Vals: []string{
			a.AlbumID, a.Title, a.ArtistName, a.Year, itoa(a.TrackCount), a.URL,
		},
		Value: a,
	}
}

func songRow(s youtube.Song) Row {
	return Row{
		Cols: []string{"id", "title", "artist", "album", "duration", "url"},
		Vals: []string{
			s.VideoID, s.Title, s.ArtistName, s.AlbumName, s.DurationText, s.URL,
		},
		Value: s,
	}
}

// anyRow renders a polymorphic search emission (Video/Channel/Playlist/Artist/Album/Song).
func anyRow(v any) Row {
	switch x := v.(type) {
	case youtube.Video:
		return videoRow(x)
	case youtube.Channel:
		return channelRow(x)
	case youtube.Playlist:
		return playlistRow(x)
	case youtube.Artist:
		return artistRow(x)
	case youtube.Album:
		return albumRow(x)
	case youtube.Song:
		return songRow(x)
	default:
		return Row{Cols: []string{"value"}, Vals: []string{""}, Value: v}
	}
}
