package youtube

import (
	"bytes"
	"context"
	"fmt"
	"html"
	"strconv"
	"strings"

	"github.com/PuerkitoBio/goquery"
)

// Captions returns the list of available caption tracks for a video.
//
// The caption list lives in the player response. The HTML-embedded
// ytInitialPlayerResponse is the reliable source (the bare InnerTube /player
// WEB call is frequently bot-gated and omits captions/streamingData), so we
// read the page first and fall back to /player only if the page yields nothing.
func (c *Client) Captions(ctx context.Context, idOrURL string) ([]CaptionTrack, error) {
	videoID := ExtractVideoID(idOrURL)
	if videoID == "" {
		videoID = idOrURL
	}
	return captionsFromPlayer(c.playerResponse(ctx, idOrURL, videoID), videoID), nil
}

// playerResponse returns the best available player-response map for a video,
// preferring the HTML page's ytInitialPlayerResponse and falling back to the
// InnerTube /player call.
func (c *Client) playerResponse(ctx context.Context, idOrURL, videoID string) map[string]any {
	if data, _, err := c.FetchPageData(ctx, NormalizeVideoURL(idOrURL)); err == nil && data != nil {
		if pr, ok := data.PlayerResp.(map[string]any); ok && pr != nil {
			return pr
		}
	}
	if pr, err := NewInnerTube(c).Player(ctx, videoID); err == nil {
		return pr
	}
	return nil
}

func captionsFromPlayer(playerResp map[string]any, videoID string) []CaptionTrack {
	var tracks []CaptionTrack
	if caps := mapValue(playerResp, "captions"); caps != nil {
		if renderer := mapValue(caps, "playerCaptionsTracklistRenderer"); renderer != nil {
			for _, item := range arrayValue(renderer["captionTracks"]) {
				m := mapValue(item, "")
				ct := CaptionTrack{
					VideoID:         videoID,
					LanguageCode:    stringValue(m["languageCode"]),
					Name:            extractText(m["name"]),
					BaseURL:         stringValue(m["baseUrl"]),
					Kind:            stringValue(m["kind"]),
					IsAutoGenerated: stringValue(m["kind"]) == "asr",
				}
				if ct.LanguageCode != "" && ct.BaseURL != "" {
					tracks = append(tracks, ct)
				}
			}
		}
	}
	return tracks
}

// Transcript fetches the timed-text XML for a video caption track and returns
// the joined plain-text transcript and the individual timed segments.
// lang selects the caption track; if empty the first non-auto track is used.
func (c *Client) Transcript(ctx context.Context, idOrURL, lang string) (string, []TranscriptSegment, error) {
	tracks, err := c.Captions(ctx, idOrURL)
	if err != nil {
		return "", nil, err
	}
	if len(tracks) == 0 {
		return "", nil, fmt.Errorf("no caption tracks available for %s", idOrURL)
	}
	track := pickCaptionTrack(tracks, lang)
	if track == nil {
		return "", nil, fmt.Errorf("no caption track for lang %q", lang)
	}

	// The default timed-text response is XML with <text start= dur=> nodes,
	// which parseTimedTextXML handles. We deliberately do not force fmt=srv3
	// (that format uses <p t= d=> nodes instead).
	raw, err := c.FetchTimedText(ctx, track.BaseURL)
	if err != nil {
		return "", nil, fmt.Errorf("fetch timed text: %w", err)
	}

	segs, err := parseTimedTextXML(raw)
	if err != nil {
		return "", nil, fmt.Errorf("parse timed text: %w", err)
	}

	var lines []string
	for _, s := range segs {
		if t := cleanWhitespace(s.Text); t != "" {
			lines = append(lines, t)
		}
	}
	return strings.Join(lines, "\n"), segs, nil
}

// Formats returns the streaming formats for a video.
//
// Like Captions, this reads the HTML-embedded player response first (it carries
// streamingData reliably) and falls back to the InnerTube /player call.
func (c *Client) Formats(ctx context.Context, idOrURL string) ([]VideoFormat, error) {
	videoID := ExtractVideoID(idOrURL)
	if videoID == "" {
		videoID = idOrURL
	}
	return ParseVideoFormats(c.playerResponse(ctx, idOrURL, videoID), videoID), nil
}

// parseTimedTextXML parses YouTube's timed-text XML (<text start= dur=> nodes).
// It handles both the srv3 XML format and falls back to goquery parsing.
func parseTimedTextXML(raw []byte) ([]TranscriptSegment, error) {
	doc, err := goquery.NewDocumentFromReader(bytes.NewReader(raw))
	if err != nil {
		return nil, err
	}
	var segs []TranscriptSegment
	// Default format: <transcript><text start= dur=>...</text>.
	doc.Find("text").Each(func(_ int, s *goquery.Selection) {
		startStr, _ := s.Attr("start")
		durStr, _ := s.Attr("dur")
		text := cleanWhitespace(html.UnescapeString(s.Text()))
		if text == "" {
			return
		}
		start, _ := strconv.ParseFloat(startStr, 64)
		dur, _ := strconv.ParseFloat(durStr, 64)
		segs = append(segs, TranscriptSegment{StartSeconds: start, DurSeconds: dur, Text: text})
	})
	if len(segs) > 0 {
		return segs, nil
	}
	// srv3 format: <timedtext><body><p t= d=>...</p>; t/d are in milliseconds.
	doc.Find("p").Each(func(_ int, s *goquery.Selection) {
		text := cleanWhitespace(html.UnescapeString(s.Text()))
		if text == "" {
			return
		}
		tMs, _ := strconv.ParseFloat(getAttr(s, "t"), 64)
		dMs, _ := strconv.ParseFloat(getAttr(s, "d"), 64)
		segs = append(segs, TranscriptSegment{StartSeconds: tMs / 1000, DurSeconds: dMs / 1000, Text: text})
	})
	return segs, nil
}

func getAttr(s *goquery.Selection, name string) string {
	v, _ := s.Attr(name)
	return v
}
