package youtube

import (
	"context"
	"errors"
	"fmt"
)

// ErrStop is returned by a streaming emit function to signal that no more items
// are needed. Streaming functions treat ErrStop as a clean stop (return nil).
var ErrStop = errors.New("youtube: stop iteration")

// VideoResult holds the full output of FetchVideo.
type VideoResult struct {
	Video        Video
	Formats      []VideoFormat
	Captions     []CaptionTrack
	Chapters     []Chapter
	Related      []RelatedVideo
	CommentToken string
}

// FetchVideo fetches a single video's full metadata.
//
// It always fetches the HTML page (ytInitialData + ytInitialPlayerResponse).
// If opt.Player is true, it additionally calls InnerTube /player for richer
// format and microformat data.
// If opt.Next is true, it calls InnerTube /next for chapters and related videos.
// If opt.Transcript is true, it fetches the best matching caption track
// (or the one matching opt.Lang) and populates Video.Transcript /
// Video.TranscriptLanguage.
func (c *Client) FetchVideo(ctx context.Context, idOrURL string, opt VideoOptions) (*VideoResult, error) {
	videoURL := NormalizeVideoURL(idOrURL)
	data, code, err := c.FetchPageData(ctx, videoURL)
	if err != nil {
		return nil, fmt.Errorf("fetch video page %q: %w", videoURL, err)
	}
	if code == 404 || data == nil {
		return nil, fmt.Errorf("video not found: %s", videoURL)
	}

	video, tracks, related, contToken, err := ParseVideoPage(data, videoURL)
	if err != nil {
		return nil, err
	}

	var formats []VideoFormat

	// Enrich from the HTML-embedded player response.
	if pr, ok := data.PlayerResp.(map[string]any); ok {
		ParseMicroformat(pr, video)
		formats = ParseVideoFormats(pr, video.VideoID)
	}

	it := NewInnerTube(c)

	// Optionally call /player for richer format data.
	if opt.Player {
		playerResp, playerErr := it.Player(ctx, video.VideoID)
		if playerErr == nil && playerResp != nil {
			details := ParsePlayerDetails(playerResp, video.VideoID)
			if details != nil {
				if video.Description == "" {
					video.Description = details.Description
				}
				if video.DurationSeconds == 0 {
					video.DurationSeconds = details.DurationSeconds
				}
				if video.ViewCount == 0 {
					video.ViewCount = details.ViewCount
				}
				if len(video.Tags) == 0 {
					video.Tags = details.Tags
				}
				if video.Category == "" {
					video.Category = details.Category
				}
				if video.UploadDate == "" {
					video.UploadDate = details.UploadDate
				}
				if video.PublishedAt.IsZero() {
					video.PublishedAt = details.PublishedAt
				}
				if video.LikeCount == 0 {
					video.LikeCount = details.LikeCount
				}
			}
			ParseMicroformat(playerResp, video)
			if pf := ParseVideoFormats(playerResp, video.VideoID); len(pf) > 0 {
				formats = pf
			}
			// Refresh caption tracks from /player if not yet populated.
			if len(tracks) == 0 {
				if caps, ok := playerResp["captions"].(map[string]any); ok {
					if renderer, ok := caps["playerCaptionsTracklistRenderer"].(map[string]any); ok {
						for _, item := range arrayValue(renderer["captionTracks"]) {
							m := mapValue(item, "")
							ct := CaptionTrack{
								VideoID:         video.VideoID,
								LanguageCode:    stringValue(m["languageCode"]),
								Name:            extractText(m["name"]),
								BaseURL:         stringValue(m["baseUrl"]),
								Kind:            stringValue(m["kind"]),
								IsAutoGenerated: stringValue(m["kind"]) == "asr",
							}
							if ct.LanguageCode != "" && ct.BaseURL != "" {
								tracks = append(tracks, ct)
							}
						}
					}
				}
			}
		}
	}

	var chapters []Chapter

	// Optionally call /next for chapters, more related, and comment token.
	if opt.Next {
		nextResp, nextErr := it.Next(ctx, video.VideoID, "")
		if nextErr == nil && nextResp != nil {
			chapters = ParseChapters(nextResp, video.VideoID, video.Description)
			nextRelated, _ := ParseContinuationRelatedVideos(nextResp, video.VideoID)
			related = append(related, nextRelated...)
			if ct := extractCommentContinuationToken(nextResp); ct != "" {
				contToken = ct
			}
		}
	}

	// Optionally fetch transcript.
	if opt.Transcript && len(tracks) > 0 {
		track := pickCaptionTrack(tracks, opt.Lang)
		if track != nil {
			_, segs, txErr := c.Transcript(ctx, video.VideoID, track.LanguageCode)
			if txErr == nil && len(segs) > 0 {
				parts := make([]string, 0, len(segs))
				for _, s := range segs {
					if s.Text != "" {
						parts = append(parts, s.Text)
					}
				}
				video.TranscriptLanguage = track.LanguageCode
				video.Transcript = joinLines(parts)
			}
		}
	}

	result := &VideoResult{
		Video:        *video,
		Formats:      formats,
		Captions:     tracks,
		Chapters:     chapters,
		Related:      related,
		CommentToken: contToken,
	}
	return result, nil
}

// pickCaptionTrack selects the best caption track for a given language code.
// If lang is empty, the first non-auto track is preferred; otherwise the first
// track matching the lang prefix is returned.
func pickCaptionTrack(tracks []CaptionTrack, lang string) *CaptionTrack {
	if len(tracks) == 0 {
		return nil
	}
	if lang != "" {
		for i := range tracks {
			if tracks[i].LanguageCode == lang {
				return &tracks[i]
			}
		}
		// Partial match (e.g. "en" matches "en-US").
		for i := range tracks {
			if len(tracks[i].LanguageCode) >= len(lang) && tracks[i].LanguageCode[:len(lang)] == lang {
				return &tracks[i]
			}
		}
	}
	// Prefer non-auto-generated.
	for i := range tracks {
		if !tracks[i].IsAutoGenerated {
			return &tracks[i]
		}
	}
	return &tracks[0]
}

func joinLines(parts []string) string {
	result := ""
	for i, p := range parts {
		if i > 0 {
			result += "\n"
		}
		result += p
	}
	return result
}
